import os

#for x in range(97):
	#os.system('python3 SAMRaman.py --optimizer sam --use_pre_split True --train_data_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_train_data.npy --train_labels_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_train_labels.npy --test_data_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_test_data.npy --test_labels_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_test_labels.npy --activation gelu --experiment_name covid_sam_gelu_pt_' +str(x)+ ' --input_dim 100 --num_classes 3 --spectra_intervals 25 25 25 --seed 42 --early_stopping_patience 30 --batch_size 16')
	#os.system('python3 SAMRaman.py --optimizer adam --use_pre_split True --train_data_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_train_data.npy --train_labels_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_train_labels.npy --test_data_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_test_data.npy --test_labels_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_test_labels.npy --activation gelu --experiment_name covid_adam_gelu_pt_' +str(x)+ ' --input_dim 100 --num_classes 3 --spectra_intervals 25 25 25 --seed 42 --early_stopping_patience 30 --batch_size 16')
	#os.system('python3 SAMRaman.py --model conf_cnn --optimizer sam --use_pre_split True --train_data_path datasets/pd_ad_dataset/loo_splits/pt_' +str(x)+ '_train_data.npy --train_labels_path datasets/pd_ad_dataset/loo_splits/pt_' +str(x)+ '_train_labels.npy --test_data_path datasets/pd_ad_dataset/loo_splits/pt_' +str(x)+ '_test_data.npy --test_labels_path datasets/pd_ad_dataset/loo_splits/pt_' +str(x)+ '_test_labels.npy --activation gelu --experiment_name pd_ad_conf_sam_64_pt_' +str(x)+ ' --input_dim 100 --num_classes 3 --spectra_intervals 25 25 25 --seed 42 --early_stopping_patience 30 --batch_size 64 --in_channels 1')
	#os.system('python3 SAMRaman.py --model covid_cnn --optimizer sam --use_pre_split True --train_data_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_train_data.npy --train_labels_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_train_labels.npy --test_data_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_test_data.npy --test_labels_path datasets/covid_dataset/loo_splits/pt_' +str(x)+ '_test_labels.npy --activation gelu --experiment_name covid_cnn_sam_gelu_pt_' +str(x)+ ' --input_dim 100 --num_classes 3 --spectra_intervals 25 25 25 --seed 42 --early_stopping_patience 50 --batch_size 256 --in_channels 1')

for i in range(50):
	x = i*9 + 32
	for optim in ['adam', 'sam', 'asam', 'friendlysam', 'fishersam']:
		os.system('python3 ../SAMRaman.py --optimizer ' + optim + ' --spectra_dirs datasets/data/X_2018clinical.npy datasets/data/X_2019clinical.npy --label_dirs datasets/data/y_2018clinical.npy datasets/data/y_2019clinical.npy --activation gelu --experiment_name bacteria_' + optim + '_gelu_pca_split_' + str(i) + ' --seed ' + str(x) + ' --early_stopping_patience 30 --input_dim 100 --batch_size 64')
		#os.system('python3 SAMRaman.py --model covid_cnn --optimizer '+str(optim)+' --spectra_dirs datasets/covid_dataset/0_spectra.npy datasets/covid_dataset/1_spectra.npy datasets/covid_dataset/2_spectra.npy --label_dirs datasets/covid_dataset/0_labels.npy datasets/covid_dataset/1_labels.npy datasets/covid_dataset/2_labels.npy --activation gelu --experiment_name covid_cnn_'+str(optim)+'_pca_split_' +str(i)+ ' --input_dim 100 --num_classes 3 --spectra_intervals 25 25 25 --seed ' + str(x) + ' --early_stopping_patience 15 --batch_size 64 --in_channels 1')
		#os.system('python3 SAMRaman.py --model conf_cnn --optimizer '+str(optim)+' --spectra_dirs datasets/pd_ad_dataset/0_spectra.npy datasets/pd_ad_dataset/1_spectra.npy datasets/pd_ad_dataset/2_spectra.npy --label_dirs datasets/pd_ad_dataset/0_labels.npy datasets/pd_ad_dataset/1_labels.npy datasets/pd_ad_dataset/2_labels.npy --activation gelu --experiment_name pd_ad_'+str(optim)+'_pca_split_' +str(i)+ ' --input_dim 100 --num_classes 3 --spectra_intervals 25 25 25 --seed ' + str(x) + ' --early_stopping_patience 15 --batch_size 64 --in_channels 1')


#for optim in ['asam', 'friendlysam', 'fishersam']:
#	for x in range(97):
#		os.system('python3 SAMRaman.py --model covid_cnn --optimizer '+str(optim)+' --use_pre_split True --train_data_path datasets/covid_dataset/loo_split_nopca_0/pt_' +str(x)+ '_train_data.npy --train_labels_path datasets/covid_dataset/loo_split_nopca_0/pt_' +str(x)+ '_train_labels.npy --test_data_path datasets/covid_dataset/loo_split_nopca_0/pt_' +str(x)+ '_test_data.npy --test_labels_path datasets/covid_dataset/loo_split_nopca_0/pt_' +str(x)+ '_test_labels.npy --val_data_path datasets/covid_dataset/loo_split_nopca_0/pt_' +str(x)+ '_val_data.npy --val_labels_path datasets/covid_dataset/loo_split_nopca_0/pt_' +str(x)+ '_val_labels.npy --activation gelu --experiment_name covid_loo_nopca_'+str(optim)+'_gelu_pt_' +str(x)+ ' --input_dim 900 --num_classes 3 --spectra_intervals 25 25 25 --seed 42 --early_stopping_patience 30 --batch_size 64 --in_channels 1')
#		os.system('python3 SAMRaman.py --model covid_cnn --optimizer '+str(optim)+' --use_pre_split True --train_data_path datasets/covid_dataset/loo_split_0/pt_' +str(x)+ '_train_data.npy --train_labels_path datasets/covid_dataset/loo_split_0/pt_' +str(x)+ '_train_labels.npy --test_data_path datasets/covid_dataset/loo_split_0/pt_' +str(x)+ '_test_data.npy --test_labels_path datasets/covid_dataset/loo_split_0/pt_' +str(x)+ '_test_labels.npy --val_data_path datasets/covid_dataset/loo_split_0/pt_' +str(x)+ '_val_data.npy --val_labels_path datasets/covid_dataset/loo_split_0/pt_' +str(x)+ '_val_labels.npy --activation gelu --experiment_name covid_loo_'+str(optim)+'_gelu_pt_' +str(x)+ ' --input_dim 100 --num_classes 3 --spectra_intervals 25 25 25 --seed 42 --early_stopping_patience 30 --batch_size 64 --in_channels 1')

	#for x in range(66):
	#	os.system('python3 SAMRaman.py --model conf_cnn --optimizer '+str(optim)+' --use_pre_split True --train_data_path datasets/pd_ad_dataset/loo_splits/pt_' +str(x)+ '_train_data.npy --train_labels_path datasets/pd_ad_dataset/loo_splits/pt_' +str(x)+ '_train_labels.npy --test_data_path datasets/pd_ad_dataset/loo_splits/pt_' +str(x)+ '_test_data.npy --test_labels_path datasets/pd_ad_dataset/loo_splits/pt_' +str(x)+ '_test_labels.npy --activation gelu --experiment_name pd_ad_conf_'+str(optim)+'_pt_' +str(x)+ ' --input_dim 100 --num_classes 3 --spectra_intervals 25 25 25 --seed 42 --early_stopping_patience 30 --batch_size 64 --in_channels 1')
	#for x in range(50):
	#	os.system('python3 SAMRaman.py --optimizer '+str(optim)+' --use_pre_split True --train_data_path datasets/data/loo_splits/pt_' +str(x)+ '_train_data.npy --train_labels_path datasets/data/loo_splits/pt_' +str(x)+ '_train_labels.npy --test_data_path datasets/data/loo_splits/pt_' +str(x)+ '_test_data.npy --test_labels_path datasets/data/loo_splits/pt_' +str(x)+ '_test_labels.npy --activation gelu --experiment_name bacteria_'+str(optim)+'_pt_' +str(x)+ ' --input_dim 1000 --num_classes 5 --seed 42 --early_stopping_patience 30 --batch_size 64 --in_channels 1 --keep_ratio 0.2')

'''
#SAM
for x in range(5):
	#os.system("python3 SAMRaman.py --optimizer sam --spectra_dirs datasets/covid_dataset/0_spectra.npy datasets/covid_dataset/1_spectra.npy datasets/covid_dataset/2_spectra.npy --label_dirs datasets/covid_dataset/0_labels.npy datasets/covid_dataset/1_labels.npy datasets/covid_dataset/2_labels.npy --activation gelu --experiment_name covid_classify_sam_gelu_" + str(x) + " --input_dim 900 --num_classes 3 --spectra_intervals 25 25 25 --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")
	os.system("python3 SAMRaman.py --optimizer sam --spectra_dirs datasets/data/X_2018clinical.npy datasets/data/X_2019clinical.npy --label_dirs datasets/data/y_2018clinical.npy datasets/data/y_2019clinical.npy --activation gelu --experiment_name bacteria_classify_sam_gelu_" + str(x) + " --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")
	os.system("python3 SAMRaman.py --optimizer sam --spectra_dirs datasets/pd_ad_dataset/0_spectra.npy datasets/pd_ad_dataset/1_spectra.npy datasets/pd_ad_dataset/2_spectra.npy --label_dirs datasets/pd_ad_dataset/0_labels.npy datasets/pd_ad_dataset/1_labels.npy datasets/pd_ad_dataset/2_labels.npy --activation gelu --experiment_name pd_ad_classify_sam_gelu_" + str(x) + " --input_dim 991 --num_classes 3 --spectra_intervals 25 25 25 --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")

#ASAM
for x in range(5):
	os.system("python3 SAMRaman.py --optimizer asam --spectra_dirs datasets/covid_dataset/0_spectra.npy datasets/covid_dataset/1_spectra.npy datasets/covid_dataset/2_spectra.npy --label_dirs datasets/covid_dataset/0_labels.npy datasets/covid_dataset/1_labels.npy datasets/covid_dataset/2_labels.npy --activation gelu --experiment_name covid_classify_sam_gelu_" + str(x) + " --input_dim 900 --num_classes 3 --spectra_intervals 25 25 25 --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")
	os.system("python3 SAMRaman.py --optimizer asam --spectra_dirs datasets/data/X_2018clinical.npy datasets/data/X_2019clinical.npy --label_dirs datasets/data/y_2018clinical.npy datasets/data/y_2019clinical.npy --activation gelu --experiment_name bacteria_classify_sam_gelu_" + str(x) + " --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")
	os.system("python3 SAMRaman.py --optimizer asam --spectra_dirs datasets/pd_ad_dataset/0_spectra.npy datasets/pd_ad_dataset/1_spectra.npy datasets/pd_ad_dataset/2_spectra.npy --label_dirs datasets/pd_ad_dataset/0_labels.npy datasets/pd_ad_dataset/1_labels.npy datasets/pd_ad_dataset/2_labels.npy --activation gelu --experiment_name pd_ad_classify_sam_gelu_" + str(x) + " --input_dim 991 --num_classes 3 --spectra_intervals 25 25 25 --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")


#ADAM
for x in range(5):
	os.system("python3 SAMRaman.py --optimizer adam --spectra_dirs datasets/covid_dataset/0_spectra.npy datasets/covid_dataset/1_spectra.npy datasets/covid_dataset/2_spectra.npy --label_dirs datasets/covid_dataset/0_labels.npy datasets/covid_dataset/1_labels.npy datasets/covid_dataset/2_labels.npy --activation gelu --experiment_name covid_classify_sam_gelu_" + str(x) + " --input_dim 900 --num_classes 3 --spectra_intervals 25 25 25 --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")
	os.system("python3 SAMRaman.py --optimizer adam --spectra_dirs datasets/data/X_2018clinical.npy datasets/data/X_2019clinical.npy --label_dirs datasets/data/y_2018clinical.npy datasets/data/y_2019clinical.npy --activation gelu --experiment_name bacteria_classify_sam_gelu_" + str(x) + " --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")
	os.system("python3 SAMRaman.py --optimizer adam --spectra_dirs datasets/pd_ad_dataset/0_spectra.npy datasets/pd_ad_dataset/1_spectra.npy datasets/pd_ad_dataset/2_spectra.npy --label_dirs datasets/pd_ad_dataset/0_labels.npy datasets/pd_ad_dataset/1_labels.npy datasets/pd_ad_dataset/2_labels.npy --activation gelu --experiment_name pd_ad_classify_sam_gelu_" + str(x) + " --input_dim 991 --num_classes 3 --spectra_intervals 25 25 25 --seed 4" + str(x) + " --early_stopping_patience 15 --batch_size 16")
'''